// AdsAuditor — Phase 0 spike, MAIN-world content script.
//
// Runs in the page's own JS realm (manifest "world": "MAIN"), which is required to:
//   - see `window.ytInitialPlayerResponse` and wrap `window.fetch` as YouTube's own
//     scripts use them;
//   - call methods YouTube attaches to the #movie_player element in ITS OWN realm
//     (getPlayerResponse / getCurrentTime / getVideoData). These are plain JS
//     properties on a custom element, not native DOM/IDL members, so an ISOLATED-world
//     content script looking at the "same" element sees a different wrapper and does
//     NOT see those methods. This is exactly why source A must live here.
//
// Observation only: `window.fetch` is wrapped to read a *clone* of the response; the
// original response returned to page code is never modified or delayed.
//
// THROWAWAY SPIKE CODE (Phase 0): plain JS, no build step, no TypeScript. Selectors and
// JSON paths are grouped in one place below instead of extension/utils/selectors.ts,
// which does not exist yet (that module is a Phase 1 deliverable).

(() => {
  'use strict';

  // Guard against double-injection (e.g. dev-mode extension reloads).
  if (window.__adsauditorSpikeInterceptorLoaded) return;
  window.__adsauditorSpikeInterceptorLoaded = true;

  // ---------------------------------------------------------------------------------
  // Spike-local "selectors module" — see file header note above.
  // ---------------------------------------------------------------------------------
  const SELECTORS = {
    moviePlayerId: 'movie_player',
    adBadgeElements: '[class*="ytp-ad-"]',
  };
  const AD_STATE_CLASSES = ['ad-showing', 'ad-interrupting'];

  const CHANNEL = 'adsauditor-spike';
  const CONFIRMATION_READ_DELAY_MS = 4000; // let the new video's player response settle
  const BADGE_LOG_THROTTLE_MS = 2000; // avoid re-logging the same badge class on churn
  const CONTENT_TIME_POLL_MS = 500; // granularity for the "last known content time" sample

  // Most recent videoId seen from Source A (player response). Used to attribute DOM ad
  // events to the CONTENT video, because movie_player.getVideoData().video_id reports
  // the AD's own id while an ad is playing (see sendDomAdEvent below).
  let lastSourceAVideoId = null;

  // Last playback-time sample taken while content (not an ad) was playing. Used instead
  // of a fresh getCurrentTime() read on the transition INTO an ad, because by the time
  // the MutationObserver callback fires the class has already changed and the player
  // is already reporting ad-timeline position, not the content position (well-known
  // YouTube player behavior).
  let lastKnownContentTimeSeconds = null;

  // ---------------------------------------------------------------------------------
  // postMessage bridge (MAIN -> ISOLATED), origin + session-token validated on both ends.
  // ---------------------------------------------------------------------------------

  // The session token is generated by bridge.js (ISOLATED world) and published on a DOM
  // attribute, because JS globals are NOT shared across worlds but the DOM is. There is
  // no guaranteed ordering between the two document_start content scripts, so reads are
  // retried instead of assumed to succeed on the first attempt.
  function postToBridge(type, payload, retriesLeft = 25) {
    const token = document.documentElement && document.documentElement.dataset
      ? document.documentElement.dataset.adsauditorToken
      : undefined;

    if (!token) {
      if (retriesLeft <= 0) {
        console.warn('[AdsAuditor Spike] Giving up: bridge session token never appeared.');
        return;
      }
      setTimeout(() => postToBridge(type, payload, retriesLeft - 1), 200);
      return;
    }

    window.postMessage({ channel: CHANNEL, token, type, payload }, window.location.origin);
  }

  // Shared utility: the watch page's own `v=` query parameter, read fresh at call time.
  // Unlike the player's live-reported videoId — which can be wrong for our purposes
  // (it reports an AD's own id while an ad is playing, or a PREFETCHED video's id for
  // some `fetch`-sourced player responses) — the page URL is a stable "what video is
  // this tab looking at" signal to join/filter records against during analysis.
  function getPageVideoIdFromUrl() {
    try {
      return new URLSearchParams(window.location.search).get('v');
    } catch (err) {
      return null;
    }
  }

  // ---------------------------------------------------------------------------------
  // Player response extraction (Source A)
  // ---------------------------------------------------------------------------------

  function readLoggedInState() {
    try {
      if (window.ytcfg && typeof window.ytcfg.get === 'function') {
        const value = window.ytcfg.get('LOGGED_IN');
        return typeof value === 'boolean' ? value : null;
      }
    } catch (err) {
      console.warn('[AdsAuditor Spike] Failed to read LOGGED_IN from ytcfg', err);
    }
    return null;
  }

  // Trimmed on purpose (review finding #3): earlier drafts also kept the full raw
  // sub-object per adPlacements/adSlots/playerAds entry, which at 50-300KB per record
  // across three capture paths x ~30 videos x 2 passes could plausibly blow the
  // ~10MB chrome.storage.local quota and silently lose data — and we intentionally do
  // NOT request the "unlimitedStorage" permission for a throwaway tool. Only the
  // ad-relevant fields are kept; if these best-effort paths come back null/empty for
  // real captures, that mismatch is itself useful signal for spike/RESULTS.md.
  function summarizeAdPlacement(placement) {
    // Field-verified 2026-07-02 (spike/adsauditor-spike-export-2026-07-02T20-18-33-363Z.json):
    // records with adPlacements.count 17 and 10 came back with every item's kind/offsets
    // null. Root cause: this originally read `placement.adPlacementConfig` directly, but
    // the real path in captured player responses is nested one level deeper, under a
    // renderer wrapper: `placement.adPlacementRenderer.config.adPlacementConfig`. Both
    // paths are checked — the confirmed renderer path first, the original flat path as a
    // fallback in case some other YouTube surface/experiment uses the flatter shape.
    const rendererConfig = placement
      && placement.adPlacementRenderer
      && placement.adPlacementRenderer.config
      && placement.adPlacementRenderer.config.adPlacementConfig;
    const directConfig = placement && placement.adPlacementConfig;
    const config = rendererConfig || directConfig;
    const offset = config && config.adTimeOffset;
    return {
      kind: (config && config.kind) || null,
      offsetStartMs: (offset && offset.offsetStartMilliseconds) ?? null,
      offsetEndMs: (offset && offset.offsetEndMilliseconds) ?? null,
    };
  }

  function summarizeAdSlot(slot) {
    const renderer = slot && slot.adSlotRenderer;
    const metadata = renderer && renderer.adSlotMetadata;
    return {
      slotType: (metadata && metadata.slotType) || null,
    };
  }

  function summarizePlayerAd(ad) {
    const keys = ad && typeof ad === 'object' ? Object.keys(ad) : [];
    return {
      // playerAds entries are typically a single-key wrapper naming the ad type (real
      // schema still to be confirmed by this spike); cheap best-effort type proxy.
      type: keys[0] || null,
    };
  }

  function buildPlayerResponseRecord(playerResponse, capturePath, requestPath) {
    const pr = playerResponse || {};
    // Canonical paths ONLY — never substitute a value read from anywhere else, even
    // when it looks plausible. See the `note` flag below for how a missing/malformed
    // videoDetails is surfaced instead of silently fabricating a videoId.
    const videoDetails = pr.videoDetails || {};
    const playabilityStatus = pr.playabilityStatus || {};
    const adPlacements = Array.isArray(pr.adPlacements) ? pr.adPlacements : [];
    const adSlots = Array.isArray(pr.adSlots) ? pr.adSlots : [];
    const playerAds = Array.isArray(pr.playerAds) ? pr.playerAds : [];

    const placementItems = adPlacements.map(summarizeAdPlacement);
    const slotItems = adSlots.map(summarizeAdSlot);
    const playerAdItems = playerAds.map(summarizePlayerAd);

    const record = {
      type: 'player_response',
      capturePath, // 'initial' | 'fetch' | 'getPlayerResponse'
      requestPath: requestPath || null, // network pathname for 'fetch' captures, null otherwise
      pageVideoId: getPageVideoIdFromUrl(), // v= from the watch page URL at capture time
      timestamp: new Date().toISOString(),
      videoId: videoDetails.videoId || null, // canonical path ONLY: videoDetails.videoId
      durationSeconds: videoDetails.lengthSeconds != null ? Number(videoDetails.lengthSeconds) : null,
      playabilityStatusValue: playabilityStatus.status || null, // canonical path ONLY: playabilityStatus.status
      isLiveContent: typeof videoDetails.isLiveContent === 'boolean' ? videoDetails.isLiveContent : null,
      loggedIn: readLoggedInState(),
      adPlacements: {
        present: placementItems.length > 0,
        count: placementItems.length,
        kinds: placementItems.map((item) => item.kind),
        items: placementItems,
      },
      adSlots: {
        present: slotItems.length > 0,
        count: slotItems.length,
        types: slotItems.map((item) => item.slotType),
        items: slotItems,
      },
      playerAds: {
        present: playerAdItems.length > 0,
        count: playerAdItems.length,
        items: playerAdItems,
      },
    };

    if (!videoDetails.videoId) {
      // Still store the record (e.g. useful to see that a matched endpoint returned
      // no videoDetails at all) but flag it instead of leaving a silently-null videoId
      // indistinguishable from "field genuinely absent on an otherwise normal response".
      record.note = 'no videoDetails';
    }

    return record;
  }

  function sendPlayerResponseRecord(playerResponse, capturePath, requestPath) {
    try {
      const record = buildPlayerResponseRecord(playerResponse, capturePath, requestPath);
      if (record.videoId) lastSourceAVideoId = record.videoId;
      postToBridge('PLAYER_RESPONSE_RECORD', record);
    } catch (err) {
      console.warn('[AdsAuditor Spike] Failed to build/send player response record', err);
    }
  }

  // --- Path 1: window.ytInitialPlayerResponse (full page load only) ----------------
  function waitForInitialPlayerResponse(retriesLeft) {
    if (window.ytInitialPlayerResponse) {
      sendPlayerResponseRecord(window.ytInitialPlayerResponse, 'initial');
      return;
    }
    if (retriesLeft <= 0) return; // not a watch page, or it never appeared — fine.
    setTimeout(() => waitForInitialPlayerResponse(retriesLeft - 1), 300);
  }
  waitForInitialPlayerResponse(20); // ~6s window covering slow first loads

  // --- Path 2: fetch to /youtubei/v1/player (fires on every SPA navigation) --------

  // `fetch`'s first argument can be a string, a Request (has `.url`), or a URL object
  // (no `.url`, but String(url) correctly yields its href). Falling back to
  // String(requestInput) instead of assuming `.url` exists avoids silently missing
  // URL-object calls.
  function extractRequestUrl(requestInput) {
    if (typeof requestInput === 'string') return requestInput;
    if (requestInput && typeof requestInput.url === 'string') return requestInput.url;
    try {
      return String(requestInput);
    } catch (err) {
      return '';
    }
  }

  // Field-verified 2026-07-02: a substring check (`url.includes('/youtubei/v1/player')`)
  // also matched sibling endpoints that are NOT the main player response —
  // /youtubei/v1/player/ad_break and /youtubei/v1/player/heartbeat were observed in the
  // captured export, producing garbage records (2-char "videoId": "ux",
  // "playabilityStatusValue": "by", etc. — real values read via the canonical paths,
  // just from a completely different, non-canonical endpoint's payload shape). Parsing
  // the URL and requiring the pathname to match the player endpoint exactly fixes this;
  // it does NOT filter out same-endpoint prefetches for other videos (e.g. homepage
  // preview prefetches), which is why every record also carries `pageVideoId` (see
  // buildPlayerResponseRecord) so the offline analysis can join/discard those instead.
  const PLAYER_ENDPOINT_PATHNAME = '/youtubei/v1/player';

  function getRequestPathname(url) {
    try {
      return new URL(url, window.location.origin).pathname;
    } catch (err) {
      return null;
    }
  }

  const originalFetch = window.fetch.bind(window);
  window.fetch = function patchedFetch(...args) {
    const fetchPromise = originalFetch(...args);
    try {
      const url = extractRequestUrl(args[0]);
      const pathname = getRequestPathname(url);

      if (pathname === PLAYER_ENDPOINT_PATHNAME) {
        fetchPromise
          .then((response) => {
            // Clone so the body stream consumed here never affects the original
            // response object returned to the page below — observation only.
            response
              .clone()
              .json()
              .then((data) => sendPlayerResponseRecord(data, 'fetch', pathname))
              .catch((err) => {
                console.warn('[AdsAuditor Spike] Failed to parse /youtubei/v1/player response as JSON', err);
              });
          })
          .catch(() => {
            // Original request failed; nothing to observe. Do not interfere with it.
          });
      }
    } catch (err) {
      console.warn('[AdsAuditor Spike] fetch interception error', err);
    }
    return fetchPromise; // always the original, unaltered response
  };

  // --- Path 3: movie_player.getPlayerResponse() on-demand confirmation read --------
  let confirmationTimer = null;
  function scheduleConfirmationRead(delayMs) {
    if (confirmationTimer) clearTimeout(confirmationTimer);
    confirmationTimer = setTimeout(() => {
      try {
        const el = document.getElementById(SELECTORS.moviePlayerId);
        if (el && typeof el.getPlayerResponse === 'function') {
          const pr = el.getPlayerResponse();
          if (pr) sendPlayerResponseRecord(pr, 'getPlayerResponse');
        }
      } catch (err) {
        console.warn('[AdsAuditor Spike] getPlayerResponse confirmation read failed', err);
      }
    }, delayMs);
  }
  scheduleConfirmationRead(CONFIRMATION_READ_DELAY_MS); // covers the first video too

  // ---------------------------------------------------------------------------------
  // DOM ad signals (Source B) — lives here because getCurrentTime()/getVideoData() are
  // only reachable from the MAIN world (see file header).
  // ---------------------------------------------------------------------------------

  function safeGetCurrentTime() {
    try {
      const el = document.getElementById(SELECTORS.moviePlayerId);
      if (el && typeof el.getCurrentTime === 'function') return el.getCurrentTime();
    } catch (err) {
      // ignore — player not ready
    }
    return null;
  }

  // Raw, as-reported-right-now videoId from the player. Kept for diagnostics only:
  // during an ad this reports the AD's own id, not the content video's id (well-known
  // YouTube player behavior — see review finding #2). Use watchUrlVideoId or
  // lastSourceAVideoId below for actual content-video attribution.
  function safeGetVideoId() {
    try {
      const el = document.getElementById(SELECTORS.moviePlayerId);
      if (el && typeof el.getVideoData === 'function') {
        const data = el.getVideoData();
        if (data && data.video_id) return data.video_id;
      }
    } catch (err) {
      // ignore — player not ready
    }
    return null;
  }

  function sendDomAdEvent(eventName, options) {
    const opts = options || {};
    const currentTimeSeconds = Object.prototype.hasOwnProperty.call(opts, 'currentTimeSecondsOverride')
      ? opts.currentTimeSecondsOverride
      : safeGetCurrentTime();

    postToBridge('DOM_AD_EVENT', {
      type: 'dom_ad_event',
      event: eventName,
      timestamp: new Date().toISOString(),
      currentTimeSeconds,
      playerReportedVideoId: safeGetVideoId(),
      // Stable across ad playback within the same navigation, unlike the player's
      // live-reported videoId above — see getPageVideoIdFromUrl().
      watchUrlVideoId: getPageVideoIdFromUrl(),
      lastSourceAVideoId,
      ...(opts.extraFields || {}),
    });
  }

  function classListToSet(el) {
    return new Set(el ? Array.from(el.classList) : []);
  }

  function isInAdState(classSet) {
    return AD_STATE_CLASSES.some((cls) => classSet.has(cls));
  }

  function setupMovieObserver(moviePlayerEl) {
    let previousClassSet = classListToSet(moviePlayerEl);
    const lastBadgeLogTime = new Map();

    // Prime the content-time sample immediately, then keep it fresh on an interval, so
    // an ad-start transition always has a recent pre-ad reading to fall back to instead
    // of a fresh (already-in-ad) getCurrentTime() read.
    if (!isInAdState(previousClassSet)) {
      const initial = safeGetCurrentTime();
      if (initial !== null) lastKnownContentTimeSeconds = initial;
    }
    setInterval(() => {
      if (!isInAdState(previousClassSet)) {
        const sample = safeGetCurrentTime();
        if (sample !== null) lastKnownContentTimeSeconds = sample;
      }
    }, CONTENT_TIME_POLL_MS);

    function handleClassMutation() {
      const current = classListToSet(moviePlayerEl);
      for (const cls of AD_STATE_CLASSES) {
        const was = previousClassSet.has(cls);
        const is = current.has(cls);
        // NOTE: a class added and removed again within a single MutationObserver
        // callback batch (both mutations coalesced before the callback runs) is
        // missed, since only the net was->is difference is inspected. Acceptable for
        // this spike: MutationObserver callbacks run on/near each microtask/macrotask
        // boundary, so a same-batch add+remove would imply a sub-millisecond ad, which
        // isn't a real playback scenario worth instrumenting here.
        if (was !== is) {
          const eventName = `${cls}-${is ? 'start' : 'end'}`;
          sendDomAdEvent(eventName, is ? { currentTimeSecondsOverride: lastKnownContentTimeSeconds } : undefined);
        }
      }
      previousClassSet = current;
    }

    function maybeLogBadgeElement(node) {
      // SVG elements expose `className` as an SVGAnimatedString, not a plain string —
      // stringifying it directly yields "[object SVGAnimatedString]" instead of the
      // actual class list, so fall back to getAttribute('class') when it's not a string.
      const className = typeof node.className === 'string'
        ? node.className
        : (node.getAttribute && node.getAttribute('class')) || '';
      if (!className) return;
      const now = Date.now();
      const last = lastBadgeLogTime.get(className) || 0;
      if (now - last < BADGE_LOG_THROTTLE_MS) return;
      lastBadgeLogTime.set(className, now);
      sendDomAdEvent('ad-badge-element-seen', { extraFields: { className } });
    }

    const observer = new MutationObserver((mutations) => {
      let classChanged = false;
      for (const mutation of mutations) {
        if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
          classChanged = true;
        }
        if (mutation.type === 'childList') {
          mutation.addedNodes.forEach((node) => {
            if (node.nodeType !== 1) return; // element nodes only
            if (node.matches && node.matches(SELECTORS.adBadgeElements)) {
              maybeLogBadgeElement(node);
            }
            if (node.querySelectorAll) {
              node.querySelectorAll(SELECTORS.adBadgeElements).forEach(maybeLogBadgeElement);
            }
          });
        }
      }
      if (classChanged) handleClassMutation();
    });

    observer.observe(moviePlayerEl, {
      attributes: true,
      attributeFilter: ['class'],
      childList: true,
      subtree: true,
    });
  }

  // Guards against attaching a second MutationObserver to the same element (see
  // waitForMoviePlayer below, which is now also invoked on every SPA navigation).
  let movieObserverAttached = false;

  function waitForMoviePlayer(retriesLeft) {
    if (movieObserverAttached) return;
    const el = document.getElementById(SELECTORS.moviePlayerId);
    if (el) {
      movieObserverAttached = true;
      setupMovieObserver(el);
      return;
    }
    if (retriesLeft <= 0) {
      console.warn('[AdsAuditor Spike] #movie_player not found in this attempt window; will retry on next navigation.');
      return;
    }
    setTimeout(() => waitForMoviePlayer(retriesLeft - 1), 500);
  }
  waitForMoviePlayer(30); // ~15s window covering the initial load

  // --- SPA navigation: every video change gets a fresh confirmation read -----------
  // Also re-attempts the movie_player observer attach: on the common "start on the
  // homepage, click a video later" flow, the initial ~15s window above can elapse
  // before #movie_player ever appears, which would otherwise silently lose ALL Source B
  // (DOM ad) data for the rest of the tab session. waitForMoviePlayer() is a no-op once
  // movieObserverAttached is true, so this is safe to call on every navigation.
  document.addEventListener('yt-navigate-finish', () => {
    scheduleConfirmationRead(CONFIRMATION_READ_DELAY_MS);
    waitForMoviePlayer(30);
  });
})();
